-- MySQL schema for Caro (server-authoritative)
CREATE DATABASE IF NOT EXISTS caro CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE caro;

CREATE TABLE IF NOT EXISTS users (
  username VARCHAR(50) PRIMARY KEY,
  password VARCHAR(255) NOT NULL,
  wins INT NOT NULL DEFAULT 0,
  losses INT NOT NULL DEFAULT 0,
  draws INT NOT NULL DEFAULT 0,
  elo INT NOT NULL DEFAULT 1000,
  banned_until DATETIME NULL,
  ban_reason VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS friends (
  username VARCHAR(50) NOT NULL,
  friend VARCHAR(50) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (username, friend),
  CONSTRAINT fk_friends_user FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE,
  CONSTRAINT fk_friends_friend FOREIGN KEY (friend) REFERENCES users(username) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friend_requests (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  from_user VARCHAR(50) NOT NULL,
  to_user VARCHAR(50) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  INDEX idx_fr_to (to_user),
  CONSTRAINT fk_fr_from FOREIGN KEY (from_user) REFERENCES users(username) ON DELETE CASCADE,
  CONSTRAINT fk_fr_to FOREIGN KEY (to_user) REFERENCES users(username) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS matches (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  room_id VARCHAR(64) NOT NULL,
  player_x VARCHAR(50) NOT NULL,
  player_o VARCHAR(50) NOT NULL,
  winner VARCHAR(50) NULL,
  reason VARCHAR(20) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
